=begin
#Jamm API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Api
  class ChargeMessageStatus
    UNSPECIFIED = "STATUS_UNSPECIFIED".freeze
    SUCCESS = "STATUS_SUCCESS".freeze
    FAILURE = "STATUS_FAILURE".freeze
    WAITING_EKYC = "STATUS_WAITING_EKYC".freeze
    BLOCKING = "STATUS_BLOCKING".freeze
    CANCELLED = "STATUS_CANCELLED".freeze

    def self.all_vars
      @all_vars ||= [UNSPECIFIED, SUCCESS, FAILURE, WAITING_EKYC, BLOCKING, CANCELLED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ChargeMessageStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ChargeMessageStatus"
    end
  end
end
