=begin
#Jamm API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Api
  class ChargeStatus
    UNSPECIFIED = "CHARGE_STATUS_UNSPECIFIED".freeze
    SUCCESS = "CHARGE_STATUS_SUCCESS".freeze
    FAILURE = "CHARGE_STATUS_FAILURE".freeze
    WAITING_EKYC = "CHARGE_STATUS_WAITING_EKYC".freeze
    BLOCKING = "CHARGE_STATUS_BLOCKING".freeze
    CANCELLED = "CHARGE_STATUS_CANCELLED".freeze
    REFUNDED = "CHARGE_STATUS_REFUNDED".freeze
    PENDING = "CHARGE_STATUS_PENDING".freeze

    def self.all_vars
      @all_vars ||= [UNSPECIFIED, SUCCESS, FAILURE, WAITING_EKYC, BLOCKING, CANCELLED, REFUNDED, PENDING].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ChargeStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ChargeStatus"
    end
  end
end
