=begin
#Jamm API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Api
  class ContractStatus
    UNSPECIFIED = "CONTRACT_STATUS_UNSPECIFIED".freeze
    INITIAL = "CONTRACT_STATUS_INITIAL".freeze
    APPROVED = "CONTRACT_STATUS_APPROVED".freeze
    ACTIVATED = "CONTRACT_STATUS_ACTIVATED".freeze
    WAITING_EKYC = "CONTRACT_STATUS_WAITING_EKYC".freeze
    EXPIRED = "CONTRACT_STATUS_EXPIRED".freeze
    DEACTIVATED = "CONTRACT_STATUS_DEACTIVATED".freeze
    CANCELLED = "CONTRACT_STATUS_CANCELLED".freeze
    PENDING_CHARGE = "CONTRACT_STATUS_PENDING_CHARGE".freeze

    def self.all_vars
      @all_vars ||= [UNSPECIFIED, INITIAL, APPROVED, ACTIVATED, WAITING_EKYC, EXPIRED, DEACTIVATED, CANCELLED, PENDING_CHARGE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ContractStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ContractStatus"
    end
  end
end
