=begin
#Jamm API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Api
  class DepositType
    UNSPECIFIED = "DEPOSIT_TYPE_UNSPECIFIED".freeze
    SAVINGS = "DEPOSIT_TYPE_SAVINGS".freeze
    CHECKING = "DEPOSIT_TYPE_CHECKING".freeze

    def self.all_vars
      @all_vars ||= [UNSPECIFIED, SAVINGS, CHECKING].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DepositType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DepositType"
    end
  end
end
