# frozen_string_literal: true

# #Jamm API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 1.0
#
# Generated by: https://openapi-generator.tech
# Generator version: 7.9.0
#

require 'date'
require 'time'

module Api
  class EventType
    UNSPECIFIED = 'EVENT_TYPE_UNSPECIFIED'
    CHARGE_CREATED = 'EVENT_TYPE_CHARGE_CREATED'
    CHARGE_UPDATED = 'EVENT_TYPE_CHARGE_UPDATED'
    CHARGE_SUCCESS = 'EVENT_TYPE_CHARGE_SUCCESS'
    CHARGE_FAIL = 'EVENT_TYPE_CHARGE_FAIL'
    CHARGE_CANCEL = 'EVENT_TYPE_CHARGE_CANCEL'
    CONTRACT_ACTIVATED = 'EVENT_TYPE_CONTRACT_ACTIVATED'
    USER_ACCOUNT_DELETED = 'EVENT_TYPE_USER_ACCOUNT_DELETED'
    TESTING = 'EVENT_TYPE_TESTING'

    def self.all_vars
      @all_vars ||= [UNSPECIFIED, CHARGE_CREATED, CHARGE_UPDATED, CHARGE_SUCCESS, CHARGE_FAIL, CHARGE_CANCEL, CONTRACT_ACTIVATED, USER_ACCOUNT_DELETED, TESTING].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EventType.all_vars.include?(value)

      raise "Invalid ENUM value #{value} for class #EventType"
    end
  end
end
