=begin
#Jamm API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module Api
  class OnSessionPaymentErrorCode
    UNSPECIFIED = "ON_SESSION_PAYMENT_ERROR_CODE_UNSPECIFIED".freeze
    MISSING_REDIRECT_URLS = "ON_SESSION_PAYMENT_ERROR_CODE_MISSING_REDIRECT_URLS".freeze
    MISSING_REQUIRED_PARAMETERS = "ON_SESSION_PAYMENT_ERROR_CODE_MISSING_REQUIRED_PARAMETERS".freeze
    MISSING_CHARGE = "ON_SESSION_PAYMENT_ERROR_CODE_MISSING_CHARGE".freeze
    CUSTOMER_NOT_FOUND = "ON_SESSION_PAYMENT_ERROR_CODE_CUSTOMER_NOT_FOUND".freeze
    CUSTOMER_INACTIVE = "ON_SESSION_PAYMENT_ERROR_CODE_CUSTOMER_INACTIVE".freeze
    MERCHANT_CUSTOMER_ALREADY_EXISTS = "ON_SESSION_PAYMENT_ERROR_CODE_MERCHANT_CUSTOMER_ALREADY_EXISTS".freeze
    VALIDATION_FAILED = "ON_SESSION_PAYMENT_ERROR_CODE_VALIDATION_FAILED".freeze
    STRATEGY_EXECUTION_FAILED = "ON_SESSION_PAYMENT_ERROR_CODE_STRATEGY_EXECUTION_FAILED".freeze
    INVALID_PAYMENT_STRATEGY = "ON_SESSION_PAYMENT_ERROR_CODE_INVALID_PAYMENT_STRATEGY".freeze

    def self.all_vars
      @all_vars ||= [UNSPECIFIED, MISSING_REDIRECT_URLS, MISSING_REQUIRED_PARAMETERS, MISSING_CHARGE, CUSTOMER_NOT_FOUND, CUSTOMER_INACTIVE, MERCHANT_CUSTOMER_ALREADY_EXISTS, VALIDATION_FAILED, STRATEGY_EXECUTION_FAILED, INVALID_PAYMENT_STRATEGY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if OnSessionPaymentErrorCode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #OnSessionPaymentErrorCode"
    end
  end
end
